Repository Team-Go-Local/go_local_frontend, pull requests merged in 2021-02, with the labels that each got.

#29 Add mini_racer Gem to pass Travis test
  Gemfile
  Gemfile.lock
Labels: Setup, Travic CI, bug, frontend

#28 Oauth
  Gemfile
  Gemfile.lock
  README.md
  app/assets/images/Screen Shot 2021-02-24 at 3.27.58 PM.png
  app/controllers/sessions_controller.rb
  app/controllers/welcome_controller.rb
  app/models/user.rb
  app/views/welcome/index.html.erb
  config/initializers/omniauth.rb
  config/routes.rb
  spec/features/welcome/index_spec.rb
Labels: frontend

#35 Oauth
  app/controllers/application_controller.rb
  app/controllers/dashboard_controller.rb
  app/controllers/sessions_controller.rb
  app/models/user.rb
  app/views/dashboard/show.html.erb
  app/views/layouts/application.html.erb
  config/routes.rb
  db/migrate/20210225224001_add_uid_to_user.rb
  db/migrate/20210225232513_change_uid_to_big_int.rb
  db/migrate/20210225232941_change_uid_to_string.rb
  db/schema.rb
  spec/features/user_logs_in_with_google_spec.rb
  spec/features/welcome/index_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/factories.rb
Labels: bug, frontend, iteration 1

#45 Refactor styling
  .gitignore
  app/assets/stylesheets/application.scss
  app/controllers/excursions_controller.rb
  app/facades/excursions_facade.rb
  app/services/excursions_service.rb
  app/views/dashboard/show.html.erb
  app/views/layouts/application.html.erb
  app/views/welcome/index.html.erb
  spec/facades/excursion_facade_spec.rb
  spec/features/excursions/user_can_create_excursion_spec.rb
  spec/features/excursions/user_can_edit_existing_excursion_spec.rb
  spec/fixtures/excursion_response.json
  spec/rails_helper.rb
  spec/services/excursions_service_spec.rb
Labels: frontend
