Repository Team-Go-Local/go_local_frontend, pull requests merged in 2021-03, with the labels that each got.

#48 Create user
  app/controllers/sessions_controller.rb
  spec/features/user_logs_in_with_google_spec.rb
  spec/features/welcome/index_spec.rb
  spec/support/factories.rb
Labels: frontend

#49 Explore page
  app/controllers/explore_controller.rb
  app/facades/excursions_facade.rb
  app/poros/excursion.rb
  app/services/excursions_service.rb
  app/views/dashboard/show.html.erb
  app/views/explore/index.html.erb
  config/routes.rb
  spec/facades/excursion_facade_spec.rb
  spec/features/explore/index_spec.rb
  spec/fixtures/all_excursions.json
  spec/services/excursions_service_spec.rb
  spec/support/factories.rb
Labels: frontend

#51 Add snippet to include engine Yarn
  package.json
Labels: Heroku

#52 Change excursion title Faker generator
  spec/support/factories.rb
Labels: bug

#55 Fix user create
  .gitignore
  app/controllers/explore_controller.rb
  app/controllers/sessions_controller.rb
  app/services/excursions_service.rb
  spec/facades/excursion_facade_spec.rb
  spec/features/dashboard/show_spec.rb
  spec/features/excursions/create_excursion_spec.rb
  spec/features/excursions/user_can_delete_excursion_spec.rb
  spec/features/excursions/user_can_edit_existing_excursion_spec.rb
  spec/features/explore/index_spec.rb
  spec/features/user_logs_in_with_google_spec.rb
  spec/features/welcome/index_spec.rb
  spec/services/excursions_service_spec.rb
Labels: Heroku, bug, frontend

#56 Styling
  app/assets/images/british-columbia.jpeg
  app/assets/images/circle-logo.png
  app/assets/images/ishan.jpg
  app/assets/images/logo.png
  app/assets/images/square-logo.png
  app/assets/images/water.jpg
  app/assets/images/white.png
  app/assets/stylesheets/application.scss
  app/services/excursions_service.rb
  app/views/dashboard/show.html.erb
  app/views/excursions/edit.html.erb
  app/views/excursions/new.html.erb
  app/views/explore/index.html.erb
  app/views/layouts/application.html.erb
  app/views/welcome/index.html.erb
  spec/features/dashboard/show_spec.rb
  spec/features/excursions/create_excursion_spec.rb
  spec/features/excursions/user_can_delete_excursion_spec.rb
  spec/features/excursions/user_can_edit_existing_excursion_spec.rb
  spec/features/explore/index_spec.rb
Labels: frontend

#64 Unfavorite action
  app/controllers/excursions_controller.rb
  app/controllers/explore_controller.rb
  app/facades/excursions_facade.rb
  app/services/excursions_service.rb
  app/views/dashboard/show.html.erb
  app/views/explore/index.html.erb
  config/routes.rb
  spec/features/explore/index_spec.rb
  spec/fixtures/vcr_cassettes/all_excursions_list.yml
  spec/fixtures/vcr_cassettes/user-favorites.yml
Labels: frontend
